"""Add product badges

Revision ID: 894ac232cabe
Revises: b69a10971e2a
Create Date: 2025-12-10 22:54:20.665426+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894ac232cabe'
down_revision: Union[str, None] = 'b69a10971e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_spicy', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_vegan', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('products', sa.Column('is_top_seller', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_top_seller')
    op.drop_column('products', 'is_vegan')
    op.drop_column('products', 'is_spicy')
    # ### end Alembic commands ###

