"""add_role_to_users

Revision ID: 47e397629a88
Revises: ca724174a33c
Create Date: 2025-11-30 18:51:29.785598+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_role_to_users

Revision ID: 47e397629a88
Revises: ca724174a33c
Create Date: 2025-11-30 18:51:29.785598+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e397629a88'
down_revision: Union[str, None] = 'ca724174a33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enum type explicitly
    user_role = sa.Enum('CLIENT', 'MANAGER', 'ADMIN', 'COURIER', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('role', user_role, nullable=False, server_default='CLIENT'))
    # Remove default after adding column
    op.alter_column('users', 'role', server_default=None)
    
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'role')
    
    # Drop Enum type
    user_role = sa.Enum('CLIENT', 'MANAGER', 'ADMIN', 'COURIER', name='userrole')
    user_role.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
