"""add manager_id to order_history

Revision ID: f435a5e034a6
Revises: f8b4a9bb14e0
Create Date: 2025-12-12 00:26:17.858586+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f435a5e034a6'
down_revision: Union[str, None] = 'f8b4a9bb14e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_history', 'users', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_history', type_='foreignkey')
    op.drop_column('order_history', 'manager_id')
    # ### end Alembic commands ###

