"""Add promo code to orders

Revision ID: aea350d982be
Revises: 5434fc15ad82
Create Date: 2025-12-07 22:25:38.150318+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea350d982be'
down_revision: Union[str, None] = '5434fc15ad82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('promo_code_name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'orders', 'promo_codes', ['promo_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'promo_code_name')
    op.drop_column('orders', 'promo_code_id')
    # ### end Alembic commands ###

