"""add show_discount_badge to promotions

Revision ID: 14f5860962b3
Revises: f435a5e034a6
Create Date: 2025-12-29 23:15:00.000000+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f5860962b3'
down_revision: Union[str, None] = 'f435a5e034a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We use server_default=sa.true() to ensure existing rows get 'true' and avoid NotNullViolation.
    # PostgreSQL supports boolean defaults as 'true' or 'false'.
    op.add_column('promotions', sa.Column('show_discount_badge', sa.Boolean(), nullable=False, server_default=sa.true()))
    
    # Optional: remove server default after adding column if you don't want it to persist as a default constraints
    # op.alter_column('promotions', 'show_discount_badge', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'show_discount_badge')
    # ### end Alembic commands ###
