"""Add callback table

Revision ID: b85d8d7ccb4a
Revises: 14f5860962b3
Create Date: 2026-01-01 22:00:33.826046+02:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85d8d7ccb4a'
down_revision: Union[str, None] = '14f5860962b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='callbackstatus'), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callbacks_id'), 'callbacks', ['id'], unique=False)
    op.create_index(op.f('ix_callbacks_phone'), 'callbacks', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_callbacks_phone'), table_name='callbacks')
    op.drop_index(op.f('ix_callbacks_id'), table_name='callbacks')
    op.drop_table('callbacks')
    # ### end Alembic commands ###
