"""Add foreign key to promo_codes product_id

Revision ID: 7806fe1744b1
Revises: 14f5860962b3
Create Date: 2026-01-18 17:17:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7806fe1744b1'
down_revision = '14f5860962b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'promo_codes', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promo_codes', type_='foreignkey')
    # ### end Alembic commands ###
